name: lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: poetry install --with dev

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Run flake8
        run: poetry run flake8 src

      - name: Run pylint
        run: poetry run pylint src

      - name: Run mypy
        run: poetry run mypy src

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Run Pytest
        run: poetry run pytest --junitxml=pytest.xml --cov=app tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
